# -*- coding: utf-8 -*-
"""Copy of AI_MOVIE_TRAILER_GENERATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Mi6N_P0n-7jthCOvstYpzyd65Zxxlve

# 🎬 AI Movie Trailer Generator

### Building an End-to-End Generative AI Application

In this workshop, we will learn how to combine:
- Prompt Engineering
- Large Language Models (LLMs)
- AI-Assisted Development
- Text-to-Speech
- Video Generation

to create an AI-powered Movie Trailer Generator.

## Step 1: Generating the Movie Story and Trailer Script

The first step is to use a Large Language Model (LLM) to generate:
- A movie storyline
- Trailer scenes
- Narration script

## Step 2: Connecting to Gemini

We will use Google's Gemini model to generate:
- Movie Story
- Trailer Scenes
- Narration Script

The model will act as the creative engine behind our Movie Trailer Generator.
"""

# Install Gemini SDK
!pip install -q google-genai

from google.colab import userdata
from google import genai

# 1. This securely grabs the key you saved in your secrets tab
my_secret_key = userdata.get("GEMINI_API_KEY")

# 2. This connects to Gemini using that key
client = genai.Client(api_key=my_secret_key)

print("Connected successfully!")

from google import genai

client = genai.Client(api_key=my_secret_key)

models = client.models.list()

for model in models:
    print(model.name)
    break

"""### Generating a Movie Story

The first step in building a Movie Trailer Generator is to create a compelling movie storyline.

We will provide:
- Movie Title
- Genre

and use Gemini to generate a short story that will later be converted into a trailer.
"""

movie_title = input("🎬 Enter Movie Title: ")
genre = input("🎭 Enter Genre: ")

# movie_title = "The Last Planet"
# genre = "Science Fiction"

prompt = f"""
Generate a short movie story.

Movie Title: {movie_title}
Genre: {genre}

The story should be exciting, cinematic, and suitable for a movie trailer.
Keep it within 150 words.
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt
)

print(response.text)

"""### Understanding the Output

Using Prompt Engineering, we provided:
- Movie Title
- Genre
- Instructions for the AI

Gemini generated a unique movie storyline based on the provided inputs.

This storyline will serve as the foundation for generating the movie trailer.

## Generating the Trailer Script

Once the story is created, we can use it to generate:

- Trailer Narration
- Scene Descriptions
- Background Music Mood

These elements will later be used to create the final trailer video.
"""

trailer_prompt = f"""
Based on the movie story below, generate a cinematic movie trailer.

Movie Story:
{response.text}

Provide the output in the following format:

Scene 1:
Visual:

Narration:

Scene 2:
Visual:

Narration:

Scene 3:
Visual:

Narration:

Background Music Mood:
"""

trailer_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=trailer_prompt
)

print(trailer_response.text)

"""### Understanding the Trailer Script

The generated trailer contains:

1. Scene Descriptions (Visuals)
2. Narration for Voice-over
3. Background Music Mood

These outputs can be passed to downstream AI systems such as:
- Image Generation Models
- Text-to-Speech Models
- Video Generation Pipelines

to create a complete movie trailer.

## Generating Trailer Narration

The trailer script contains:
- Visual descriptions
- Narration
- Background music instructions

For voice generation, we only need the narration lines.

We will ask Gemini to extract the narration and create a clean voice-over script.
"""

narration_prompt = f"""
Extract only the narration lines from the movie trailer below.

Do not include:
- Scene numbers
- Visual descriptions
- Background music instructions

Return only the narration as a continuous movie trailer voice-over.

Trailer:

{trailer_response.text}
"""

narration_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=narration_prompt
)

print(narration_response.text)

"""## Generating Voice-over

The extracted narration can be converted into speech using a Text-to-Speech (TTS) model.

This allows us to transform AI-generated text into a cinematic movie trailer voice-over.
"""

!pip install -q edge-tts

import edge_tts
import asyncio

voice_text = narration_response.text

async def generate_voice():
    communicate = edge_tts.Communicate(
        text=voice_text,
        voice="en-US-GuyNeural"
    )

    await communicate.save("/content/sample_data/trailer_voice.mp3")

await generate_voice()

print("Voice-over generated successfully!")

"""## Listening to the AI-Generated Trailer Voice-over

The narration generated by Gemini is converted into speech using a Text-to-Speech model.

This allows us to hear the movie trailer before creating the final video.
"""

from IPython.display import Audio

Audio("/content/sample_data/trailer_voice.mp3")

"""## Generating Scene Images

The trailer script contains detailed visual descriptions.

These descriptions can be used as prompts for an Image Generation Model to create cinematic scenes for the movie trailer.

## Generating AI Image Prompts

The trailer script already contains visual descriptions.

We can use Gemini to convert these descriptions into professional image-generation prompts that can be used with tools such as:
- Google ImageFX
- Gemini Image Generation
- Midjourney
- Stable Diffusion

This demonstrates how Large Language Models can orchestrate other AI systems.
"""

image_prompt_request = f"""
From the trailer below, extract the first 3 scenes.

For each scene, create a highly detailed cinematic image generation prompt.

The prompt should include:
- Environment
- Lighting
- Camera angle
- Mood
- Cinematic details

Return the output in the following format:

Scene 1 Prompt:
...

Scene 2 Prompt:
...

Scene 3 Prompt:
...

Trailer:

{trailer_response.text}
"""

image_prompt_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=image_prompt_request
)

image_prompts = image_prompt_response.text

print(image_prompts)

"""## Creating the Trailer Video

The final step is to combine:
- Generated Images
- AI Voice-over

to create a movie trailer video.
"""

!pip install -q moviepy

import moviepy

print(moviepy.__version__)

from moviepy.editor import (
    ImageClip,
    AudioFileClip,
    concatenate_videoclips
)

print("MoviePy imported successfully!")

from PIL import Image

for img_file in [
    "/content/sample_data/glass memoery i-1.jpg",
    "/content/sample_data/222 generated_image (18).jpg",
    "/content/sample_data/3 generated_image (20).jpg",
    "/content/sample_data/4 magicstudio-art (19).jpg",
    "/content/sample_data/glass memory i-13.jpg"
]:
    img = Image.open(img_file)
    print(img_file, img.size)

from moviepy.editor import AudioFileClip

audio = AudioFileClip("/content/sample_data/trailer_voice.mp3")

print("Duration:", audio.duration)

from moviepy.editor import (
    ImageClip,
    AudioFileClip,
    concatenate_videoclips
)

# Load narration
audio = AudioFileClip("/content/sample_data/trailer_voice.mp3")

# Calculate duration per scene
scene_duration = audio.duration / 3

# Create image clips
clip1 = ImageClip("/content/sample_data/glass memoery i-1.jpg").set_duration(scene_duration)
clip2 = ImageClip("/content/sample_data/222 generated_image (18).jpg").set_duration(scene_duration)
clip3 = ImageClip("/content/sample_data/3 generated_image (20).jpg").set_duration(scene_duration)
clip4 = ImageClip("/content/sample_data/4 magicstudio-art (19).jpg").set_duration(scene_duration)
clip5 = ImageClip("/content/sample_data/glass memory i-13.jpg").set_duration(scene_duration)


# Combine clips
video = concatenate_videoclips([clip1, clip2, clip3 , clip4 ,clip5])
# Add narration
video = video.set_audio(audio)

# Export
video.write_videofile(
    "final_movie_trailer.mp4",
    fps=24,
    codec="libx264",
    audio_codec="aac"
)

from IPython.display import Video

Video("final_movie_trailer.mp4", embed=True)

def zoom_out_effect(clip, zoom_ratio=0.04):
    def effect(get_frame, t):
        img = get_frame(t)

        import cv2
        import numpy as np

        h, w = img.shape[:2]

        scale = 1 + zoom_ratio * (clip.duration - t)

        new_w = int(w / scale)
        new_h = int(h / scale)

        x1 = (w - new_w) // 2
        y1 = (h - new_h) // 2

        cropped = img[y1:y1+new_h, x1:x1+new_w]

        return cv2.resize(cropped, (w, h))

    return clip.fl(effect)

def zoom_in_effect(clip, zoom_ratio=0.04):
    def effect(get_frame, t):
        img = get_frame(t)

        import cv2

        h, w = img.shape[:2]

        scale = 1 + zoom_ratio * t

        new_w = int(w / scale)
        new_h = int(h / scale)

        x1 = (w - new_w) // 2
        y1 = (h - new_h) // 2

        cropped = img[y1:y1+new_h, x1:x1+new_w]

        return cv2.resize(cropped, (w, h))

    return clip.fl(effect)

from moviepy.editor import (
    ImageClip,
    AudioFileClip,
    concatenate_videoclips
)

audio = AudioFileClip(
    "/content/sample_data/trailer_voice.mp3"
)

scene_duration = audio.duration / 5

clip1 = ImageClip(
    "/content/sample_data/glass memoery i-1.jpg"
).set_duration(scene_duration)

clip1 = zoom_in_effect(clip1)

clip2 = ImageClip(
    "/content/sample_data/222 generated_image (18).jpg"
).set_duration(scene_duration)

clip2 = zoom_out_effect(clip2)

clip3 = ImageClip(
    "/content/sample_data/3 generated_image (20).jpg"
).set_duration(scene_duration)

clip3 = zoom_in_effect(clip3)

clip4 = ImageClip(
    "/content/sample_data/4 magicstudio-art (19).jpg"
).set_duration(scene_duration)

clip4 = zoom_in_effect(clip4)

clip5 = ImageClip(
    "/content/sample_data/glass memory i-13.jpg"
).set_duration(scene_duration)

clip5 = zoom_in_effect(clip5)

# Fade transitions
clip1 = clip1.fadein(1).fadeout(1)
clip2 = clip2.fadein(1).fadeout(1)
clip3 = clip3.fadein(1).fadeout(1)
clip4 = clip4.fadein(1).fadeout(1)
clip5 = clip5.fadein(1).fadeout(1)

video = concatenate_videoclips(
    [clip1, clip2, clip3,clip4,clip5],
    method="compose"
)

video = video.set_audio(audio)

video.write_videofile(
    "cinematic_trailer.mp4",
    fps=24,
    codec="libx264",
    audio_codec="aac"
)

# Calculate duration dynamically for all 13 scenes
scene_duration = audio.duration / 13

# Process all clips dynamically from your existing list
clips = []
for i, path in enumerate(image_paths):
    # Load and set duration
    clip = ImageClip(path).set_duration(scene_duration)

    # Alternate zoom effects (even indices zoom in, odd indices zoom out)
    if i % 2 == 0:
        clip = zoom_in_effect(clip)
    else:
        clip = zoom_out_effect(clip)

    # Apply fade transitions
    clip = clip.fadein(1).fadeout(1)

    clips.append(clip)

# Concatenate all clips together
video = concatenate_videoclips(clips, method="compose")
video = video.set_audio(audio)

# Export the final video
video.write_videofile(
    "cinematic_trailer.mp4",
    fps=24,
    codec="libx264",
    audio_codec="aac"
)

from IPython.display import Video

Video("cinematic_trailer.mp4", embed=True)

